### ISSUE TITLE
AYSAT command

### ISSUE THREAD

**Issue by DanValnicek** [tea-bot-project/tea-bot#13]
prikaz !AYSAT ktory by postol link videa https://www.youtube.com/watch?v=oHC1230OpOg

**Comment by FajsiEx** [comment]
will be added to qr in somewhere in beta

**Comment by FajsiEx** [comment]
Depends on #24

**Comment by FajsiEx** [comment]
#24 but you can link video without it using the plain qr type, but gif with "file" qr type would be more suitable imo.

**Comment by FajsiEx** [comment]
@DanValnicek wanna do it or?

**Comment by DanValnicek** [comment]
OK.

**Comment by FajsiEx** [comment]
done in #87
